### ISSUE TITLE
please upload the training and test source code

### ISSUE THREAD

**Issue by dragen1860** [andreas128/SRFlow#1]
Dear author:
   You SRFlow work is really insightful. Lots of researchers just like me are looking forward to try your models. Please kindly share the source code asap. Thank you very much!

**Comment by andreas128** [comment]
Great to hear that you like SRFlow! We're still in the legal process of releasing the code. Hope we get clearance soon!

**Comment by machanic** [comment]
When will you upload the source code?

**Comment by andreas128** [comment]
The legal department notified us that they are still working on it. Hope we can publish the code soon!

**Comment by andreas128** [comment]
We have good news! The SRFlow model code, as well as the trained models, are now public.

We are not yet allowed to publish the training procedure. But hopefully we can do that soon.

Please let us know if you have any feedback or questions.

**Comment by andreas128** [comment]
Sure, go ahead!

We hope that we can soon also publish the original training code.

**Comment by thunanguyen** [comment]
> Sure, go ahead!
> 
> We hope that we can soon also publish the original training code.

I mean is it possible ?

**Comment by erqiangli** [comment]
> > We have good news! The SRFlow model code, as well as the trained models, are now public.
> > We are not yet allowed to publish the training procedure. But hopefully we can do that soon.
> > Please let us know if you have any feedback or questions.
> 
> With the current code, can I use the code for the model and implement a simple training script ?

Do you have use the code for the model and implement a simple training script ?

**Comment by martin-danelljan** [comment]
Hi. We just got thumbs up for publishing training code, so we will do this in the week after the holidays.

**Comment by erqiangli** [comment]
> Hi. We just got thumbs up for publishing training code, so we will do this in the week after the holidays.


Great ！Good news indeed！Is it okay before this weekend？

**Comment by martin-danelljan** [comment]
It is up now!
