### ISSUE TITLE
why only take $z_L$ into consideration instead of $z=(z_l)_l=1^L$

### ISSUE THREAD

**Issue by wyf0912** [andreas128/SRFlow#33]
Thanks for sharing the code.

I have a confusion that you only maximize the term $p(z_L|x)$ in the code. 
However, the image is obtained by $z=(z_l)_l=1^L$.

What is the reason?
Looking forward to your reply. Thanks!

**Comment by KwanghyunOn** [comment]
I have the same question too. The code doesn't optimize z[L-1] to z[1], but samples from the gaussian distribution in test time.

**Comment by kevin-on** [comment]
The log probability of the intermediate latent vectors (z[L-1] to z[1]) are added in the split layer.
You can find the code at https://github.com/andreas128/SRFlow/blob/master/code/models/modules/Split.py#L56.

**Comment by wyf0912** [comment]
Thanks a lot!
