### ISSUE TITLE
Training code request

### ISSUE THREAD

**Issue by pythonmobile** [andreas128/SRFlow#8]
Any ETA on that?

**Comment by martin-danelljan** [comment]
Hi. We just got thumbs up for publishing training code, so we will do this in the week after the holidays.

**Comment by pythonmobile** [comment]
Thanks Martin. Any chance I can train SRFlow with a 2080ti? Or is it that any reasonable size needs multiple V100s or such?

**Comment by martin-danelljan** [comment]
Hi. Yes one 2080ti should be enough at least for a slightly small model.
